train_dir   : '/media/peter/Daten/GNN/Data/PbPb/MC/eventfiles/train'
valid_dir   : '/media/peter/Daten/GNN/Data/PbPb/MC/eventfiles/valid'
dataset     : 'alicetrd'
dims        : 3
log_dir     : 'logs/test_CGNN/'
run_type    : 'new_run'
gpu         : '-1'
n_files     : 1049
n_valid     : 49
n_train     : 1000
lr_c        : 0.01
batch_size  : 25
n_iters     : 5
n_epoch     : 30
TEST_every  : 50
hid_dim     : 32
network     : 'CGNN'
optimizer: 'Adam'
loss_func: 'BinaryCrossentropy'
n_thread    : 4
log_verbosity: 3
